{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c023c8a-2dfa-4580-a576-398fead019df",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import scipy.io\n",
    "from scipy.stats import multivariate_normal\n",
    "\n",
    "\n",
    "# 1. 加载数据集\n",
    "def load_data():\n",
    "    # 加载.mat文件\n",
    "    data = scipy.io.loadmat('mnist_data.mat')\n",
    "\n",
    "    # 提取训练集和测试集\n",
    "    trX = data['trX']  # 训练数据\n",
    "    trY = data['trY'].flatten()  # 训练标签 (0表示7，1表示8)\n",
    "    tsX = data['tsX']  # 测试数据\n",
    "    tsY = data['tsY'].flatten()  # 测试标签 (0表示7，1表示8)\n",
    "    return trX, trY, tsX, tsY\n",
    "\n",
    "\n",
    "# 2. 特征提取\n",
    "def extract_features(images):\n",
    "    features = np.array([[np.mean(image), np.std(image)] for image in images])\n",
    "    return features\n",
    "\n",
    "\n",
    "# 3. 特征标准化\n",
    "def standardize_features(features, mean=None, std=None):\n",
    "    if mean is None or std is None:\n",
    "        mean = np.mean(features, axis=0)\n",
    "        std = np.std(features, axis=0)\n",
    "    standardized_features = (features - mean) / std\n",
    "    return standardized_features, mean, std\n",
    "\n",
    "\n",
    "# 4. 最大似然估计（MLE）\n",
    "def estimate_parameters(features, labels, target_label):\n",
    "    target_features = features[labels == target_label]\n",
    "    mean = np.mean(target_features, axis=0)\n",
    "    cov = np.cov(target_features, rowvar=False)\n",
    "    return mean, cov\n",
    "\n",
    "\n",
    "# 5. 朴素贝叶斯分类器\n",
    "def naive_bayes_classifier(features, mean_7, cov_7, mean_8, cov_8):\n",
    "    # 计算概率密度\n",
    "    prob_7 = multivariate_normal.pdf(features, mean=mean_7, cov=cov_7)\n",
    "    prob_8 = multivariate_normal.pdf(features, mean=mean_8, cov=cov_8)\n",
    "\n",
    "    # 预测标签\n",
    "    labels = np.where(prob_7 > prob_8, 0, 1)\n",
    "    return labels\n",
    "\n",
    "\n",
    "# 6. 逻辑回归\n",
    "def sigmoid(z):\n",
    "    z = np.clip(z, -500, 500)\n",
    "    return 1 / (1 + np.exp(-z))\n",
    "\n",
    "\n",
    "def gradient_ascent(features, labels, learning_rate=0.01, num_iterations=1000):\n",
    "    # 初始化参数\n",
    "    weights = np.zeros(features.shape[1])\n",
    "\n",
    "    # 梯度上升\n",
    "    for _ in range(num_iterations):\n",
    "        scores = np.dot(features, weights)\n",
    "        predictions = sigmoid(scores)\n",
    "        errors = labels - predictions\n",
    "        gradient = np.dot(features.T, errors)\n",
    "        weights += learning_rate * gradient\n",
    "    return weights\n",
    "\n",
    "\n",
    "# 7. 主函数\n",
    "def main():\n",
    "    # 加载数据\n",
    "    trX, trY, tsX, tsY = load_data()\n",
    "\n",
    "    # 提取特征\n",
    "    trX_new = extract_features(trX)\n",
    "    tsX_new = extract_features(tsX)\n",
    "\n",
    "    # 标准化特征\n",
    "    trX_new_standardized, tr_mean, tr_std = standardize_features(trX_new)\n",
    "    tsX_new_standardized = (tsX_new - tr_mean) / tr_std\n",
    "\n",
    "    # 估计数字“7”和“8”的分布参数\n",
    "    mean_7, cov_7 = estimate_parameters(trX_new, trY, 0)\n",
    "    mean_8, cov_8 = estimate_parameters(trX_new, trY, 1)\n",
    "\n",
    "    # 朴素贝叶斯分类器\n",
    "    test_predictions_nb = naive_bayes_classifier(tsX_new, mean_7, cov_7, mean_8, cov_8)\n",
    "    accuracy_nb = np.mean(test_predictions_nb == tsY)\n",
    "    print(f\"朴素贝叶斯分类精度: {accuracy_nb:.4f}\")\n",
    "\n",
    "    # 逻辑回归\n",
    "    learning_rate = 0.1\n",
    "    num_iterations = 10000\n",
    "    weights = gradient_ascent(trX_new_standardized, trY, learning_rate, num_iterations)\n",
    "\n",
    "    # 对测试集进行分类\n",
    "    test_scores = np.dot(tsX_new_standardized, weights)\n",
    "    test_predictions_lr = np.where(test_scores > 0.5, 1, 0)\n",
    "\n",
    "    # 计算分类精度\n",
    "    accuracy_lr = np.mean(test_predictions_lr == tsY)\n",
    "    print(f\"逻辑回归分类精度: {accuracy_lr:.4f}\")\n",
    "\n",
    "\n",
    "# 运行主函数\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
